spring.application.name=fawry-payment
spring.application.description="Fawry processes payments through multiple payment gateways"
spring.application.version="1.0.0"
spring.datasource.url=jdbc:postgresql://localhost:1000/fawary-payment
spring.datasource.username=root
spring.datasource.password=root
logging.level.org.springframework.jdbc.core=trace
spring.jpa.hibernate.ddl-auto=update
